2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T17:06:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'NoneType' object has no attribute 'text'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 91, in update_display\n    self.settings.level_min.update_value()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 220, in update_value\n    new_val = self.sender().text()\n', "AttributeError: 'NoneType' object has no attribute 'text'\n"]
2020-07-26T18:34:42|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:42|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:50|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:50|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:50|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:50|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:34:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:02|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:02|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:02|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 171, in draw_contours\n    x = int(cx[indx] - self.settings.roi_half_side)\n', "TypeError: unsupported operand type(s) for -: 'int' and 'LoggedQuantity'\n"]
2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:39:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'cnt'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'cnt'\n"]
