2020-07-26T15:22:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:18|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:22|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:24|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:26|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:28|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:30|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:32|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:34|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:36|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:03|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:13|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:18|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:21|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:25|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:28|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:31|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T16:00:13|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:15|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:18|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:20|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:07:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:08:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:08:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
